/**
 * List of Pokémon types.
 */
export const types = [
  "Normal", "Fire", "Water", "Grass", "Electric", "Ice",
  "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug",
  "Rock", "Ghost", "Dragon", "Dark", "Steel"
]

/**
 * Mapping of Pokémon types to Tailwind CSS classes for background and text color.
 */
export const typeColors: Record<string, string> = {
  Fire: "bg-orange-100 text-orange-700",
  Water: "bg-blue-100 text-blue-700",
  Grass: "bg-green-100 text-green-700",
  Electric: "bg-yellow-100 text-yellow-700",
  Poison: "bg-purple-100 text-purple-700",
  Psychic: "bg-pink-100 text-pink-700",
  Ice: "bg-cyan-100 text-cyan-700",
  Dragon: "bg-indigo-100 text-indigo-700",
  Dark: "bg-gray-900 text-white",
  Rock: "bg-yellow-200 text-yellow-800",
  Ground: "bg-orange-200 text-orange-800",
  Ghost: "bg-violet-100 text-violet-700",
  Bug: "bg-lime-100 text-lime-700",
  Steel: "bg-slate-100 text-slate-700",
  Fighting: "bg-red-100 text-red-700",
  Normal: "bg-stone-100 text-stone-600",
  Flying: "bg-sky-100 text-sky-700",
  Fairy: "bg-pink-300 text-pink-700",
}

export const typeHexColors: Record<string, string> = {
  Normal:   "#A8A878",
  Fire:     "#F08030",
  Water:    "#6890F0",
  Electric: "#F8D030",
  Grass:    "#78C850",
  Ice:      "#98D8D8",
  Fighting: "#C03028",
  Poison:   "#A040A0",
  Ground:   "#E0C068",
  Flying:   "#A890F0",
  Psychic:  "#F85888",
  Bug:      "#A8B820",
  Rock:     "#B8A038",
  Ghost:    "#705898",
  Dragon:   "#7038F8",
  Dark:     "#705848",
  Steel:    "#B8B8D0",
  Fairy:    "#EE99AC",
}


export const EXCLUDED_POKEMON = [
  "mega abomasnow",
  "mega absol",
  "aegislash shield forme",
  "aegislash blade forme",
  "mega aerodactyl",
  "mega aggron",
  "mega alakazam",
  "mega altaria",
  "mega ampharos",
  "mega audino",
  "mega banette",
  "mega beedrill",
  "mega blastoise",
  "mega blaziken",
  "mega camerupt",
  "mega charizard x",
  "mega charizard y",
  "mega diancie",
  "mega gallade",
  "mega garchomp",
  "mega gardevoir",
  "mega gengar",
  "mega glalie",
  "mega gyarados",
  "mega heracross",
  "mega houndoom",
  "mega kangaskhan",
  "mega latias",
  "mega latios",
  "mega lopunny",
  "mega lucario",
  "mega manectric",
  "mega mawile",
  "mega medicham",
  "mega metagross",
  "mega mewtwo x",
  "mega mewtwo y",
  "mega pidgeot",
  "mega pinsir",
  "mega rayquaza",
  "mega sableye",
  "mega salamence",
  "mega sceptile",
  "mega scizor",
  "mega sharpedo",
  "mega slowbro",
  "mega steelix",
  "mega swampert",
  "mega tyranitar",
  "mega venusaur",
  "dudunsparce two-segment form",
  "dudunsparce three-segment form",
  "partner eevee",
  "farfetch'd",
  "indeedee male",
  "indeedee female",
  "galarian articuno",
  "galarian corsola",
  "darmanitan galarian standard mode",
  "darmanitan galarian zen mode",
  "galarian darumaka",
  "galarian farfetch'd",
  "galarian linoone",
  "galarian meowth",
  "galarian moltres",
  "galarian mr. mime",
  "galarian ponyta",
  "galarian rapidash",
  "galarian slowbro",
  "galarian slowking",
  "galarian slowpoke",
  "galarian stunfisk",
  "galarian weezing",
  "galarian yamask",
  "galarian zapdos",
  "galarian zigzagoon",
  "ursaluna bloodmoon",
  "type: null",
  "hisuian arcanine",
  "hisuian avalugg",
  "hisuian braviary",
  "hisuian decidueye",
  "hisuian electrode",
  "hisuian goodra",
  "hisuian growlithe",
  "hisuian lilligant",
  "hisuian qwilfish",
  "hisuian samurott",
  "hisuian sliggoo",
  "hisuian sneasel",
  "hisuian typhlosion",
  "hisuian voltorb",
  "hisuian zoroark",
  "hisuian zorua",
  "terapagos terastal form",
  "terapagos normal form",
  "terapagos stellar form",
  "alolan diglett",
  "alolan dugtrio",
  "alolan exeggutor",
  "alolan geodude",
  "alolan golem",
  "alolan graveler",
  "alolan grimer",
  "alolan marowak",
  "alolan meowth",
  "alolan muk",
  "alolan ninetales",
  "alolan persian",
  "alolan raichu",
  "alolan raticate",
  "alolan rattata",
  "alolan sandshrew",
  "alolan sandslash",
  "alolan vulpix",
  "castform sunny form",
  "darmanitan standard mode",
  "darmanitan zen mode",
  "gouging fire",
  "primal groudon",
  "primal kyogre",
  "tauros blaze breed",
  "oricorio baile style",
  "ogerpon hearthflame mask",
  "iron moth",
  "basculegion male",
  "basculegion female",
  "basculin red-striped form",
  "basculin blue-striped form",
  "basculin white-striped form",
  "castform rainy form",
  "ash-greninja",
  "iron bundle",
  "castform snowy form",
  "deoxys normal forme",
  "deoxys attack forme",
  "deoxys defense forme",
  "deoxys speed forme",
  "dialga origin forme",
  "enamorus incarnate forme",
  "enamorus therian forme",
  "gimmighoul chest form",
  "gimmighoul roaming form",
  "giratina altered forme",
  "giratina origin forme",
  "keldeo ordinary form",
  "keldeo resolute form",
  "landorus incarnate forme",
  "landorus therian forme",
  "lycanroc midday form",
  "lycanroc midnight form",
  "lycanroc dusk form",
  "meloetta aria forme",
  "meloetta pirouette forme",
  "minior meteor form",
  "minior core form",
  "palafin zero form",
  "palafin hero form",
  "palkia origin forme",
  "shaymin land forme",
  "shaymin sky forme",
  "tatsugiri curly form",
  "tatsugiri droopy form",
  "tatsugiri stretchy form",
  "thundurus incarnate forme",
  "thundurus therian forme",
  "tornadus incarnate forme",
  "tornadus therian forme",
  "toxtricity amped form",
  "toxtricity low key form",
  "wishiwashi solo form",
  "wishiwashi school form",
  "zygarde 50% forme",
  "zygarde 10% forme",
  "zygarde complete forme",
  "walking wake",
  "urshifu rapid strike style",
  "tauros aqua breed",
  "tapu fini",
  "wash rotom",
  "ogerpon wellspring mask",
  "brute bonnet",
  "gourgeist average size",
  "gourgeist super size",
  "gourgeist large size",
  "gourgeist small size",
  "iron leaves",
  "ogerpon teal mask",
  "ogerpon cornerstone mask",
  "wormadam plant cloak",
  "tapu bulu",
  "mow rotom",
  "pumpkaboo average size",
  "pumpkaboo small size",
  "pumpkaboo large size",
  "pumpkaboo super size",
  "pumpkaboo super size",
  "iron hands",
  "iron thorns",
  "morpeko full belly mode",
  "morpeko hangry mode",
  "oricorio pom-pom style",
  "partner pikachu",
  "raging bolt",
  "sandy shocks",
  "heat rotom",
  "fan rotom",
  "frost rotom",
  "tapu koko",
  "calyrex ice rider",
  "eiscue ice face",
  "eiscue noice face",
  "white kyurem",
  "black kyurem",
  "mr. rime",
  "great tusk",
  "iron valiant",
  "sirfetch'd",
  "slither wing",
  "tauros combat breed",
  "zamazenta hero of many battles",
  "zamazenta crowned shield",
  "urshifu single strike style",
  "eternatus eternamax",
  "nidoran♀ (female) nidoran♀",
  "nidoran♂ (male) nidoran♂",
  "paldean wooper",
  "iron treads",
  "wormadam sandy cloak",
  "iron jugulis",
  "oricorio pa'u style",
  "oricorio sensu style",
  "squawkabilly green plumage",
  "squawkabilly blue plumage",
  "squawkabilly yellow plumage",
  "squawkabilly white plumage",
  "calyrex shadow rider",
  "hoopa confined",
  "hoopa unbound",
  "iron boulder",
  "iron crown",
  "meowstic male",
  "meowstic female",
  "mime jr.",
  "mr. mime",
  "ultra necrozma",
  "dawn wings necrozma",
  "dusk mane necrozma",
  "tapu lele",
  "burmy plant cloak",
  "burmy sandy cloak",
  "burmy trash cloak",
  "wormadam trash cloak",
  "flutter mane",
  "roaring moon",
  "zacian crowned sword"



]

